name: Compilar Mod de Geode

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Compilar en Windows
    runs-on: windows-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Compilar el mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: nightly

      - name: Subir el archivo .geode
        uses: actions/upload-artifact@v4
        with:
          name: PracticeReplayer
          path: '*.geode'
